backend:
  name: github
  repo: sinnerschrader/sinnerschrader-reboot
  branch: main
  base_url: https://k741x3mcij.execute-api.eu-central-1.amazonaws.com
  auth_endpoint: /prod/auth

media_library:
  name: "disabled"

publish_mode: editorial_workflow

collections:
  - label: "Job"
    name: "job"
    folder: "src/jobs"
    create: true
    delete: true
    slug: "{{title}}-{{location}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"

      - label: "City"
        name: "location"
        widget: "select"
        options:
          - { label: "Hamburg", value: "hamburg" }
          - { label: "Munich", value: "munich" }
          - { label: "Frankfurt", value: "frankfurt" }
          - { label: "Berlin", value: "berlin" }
          - { label: "Prague", value: "prague" }
          - { label: "Zurich", value: "zurich" }

      - label: "Discipline"
        name: "discipline"
        widget: "select"
        options:
          - { label: "Tech", value: "tech" }
          - { label: "Creative", value: "creative" }
          - { label: "Strategy", value: "strategy" }
          - { label: "Account Management", value: "account management" }
          - { label: "Corporate Functions", value: "corporate functions" }

      - label: "Contact"
        name: "contact"
        widget: "select"
        options:
          - { label: "Vicky", value: "vicky" }

      - { label: "Description", name: "description", widget: "markdown" }

      - { label: "Details", name: "details", widget: "markdown" }
