name: Run accessibility check

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: |
          npm ci
          npm run build
          npm run a11y-check
